services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  client:
     stdin_open: true
     build:
       context: ./web
       dockerfile: Dockerfile.dev
     ports:
       - "3000:3000"
